[2024-07-08T17:20:24.549+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T17:20:25.668+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-07-08T17:20:26.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-07-08T17:20:26.172+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T17:20:27.284+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-06-22 00:00:00+00:00
[2024-07-08T17:20:27.758+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=275) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T17:20:27.787+0000] {standard_task_runner.py:63} INFO - Started process 296 to run task
[2024-07-08T17:20:27.945+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'insert_book_data', 'scheduled__2024-06-22T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpf1471rr_']
[2024-07-08T17:20:27.970+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask insert_book_data
[2024-07-08T17:20:31.141+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-22T00:00:00+00:00 [running]> on host 75379950ed90
[2024-07-08T17:20:33.144+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-22T00:00:00+00:00'
[2024-07-08T17:20:33.367+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T17:20:33.631+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T17:20:33.661+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 95, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-07-08T17:20:33.804+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=insert_book_data, run_id=scheduled__2024-06-22T00:00:00+00:00, execution_date=20240622T000000, start_date=20240708T172025, end_date=20240708T172033
[2024-07-08T17:20:34.364+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task insert_book_data (No book data found; 296)
[2024-07-08T17:20:34.945+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T17:20:35.272+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
