[2024-07-08T17:21:08.753+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T17:21:09.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-07-04T00:00:00+00:00 [queued]>
[2024-07-08T17:21:09.644+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-07-04T00:00:00+00:00 [queued]>
[2024-07-08T17:21:09.654+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T17:21:09.867+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-07-04 00:00:00+00:00
[2024-07-08T17:21:10.181+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=295) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T17:21:10.224+0000] {standard_task_runner.py:63} INFO - Started process 308 to run task
[2024-07-08T17:21:10.277+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'insert_book_data', 'scheduled__2024-07-04T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpioy3ytb7']
[2024-07-08T17:21:10.423+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask insert_book_data
[2024-07-08T17:21:11.771+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-07-04T00:00:00+00:00 [running]> on host 75379950ed90
[2024-07-08T17:21:15.171+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-04T00:00:00+00:00'
[2024-07-08T17:21:15.275+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T17:21:15.769+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T17:21:15.813+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 95, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-07-08T17:21:15.923+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=insert_book_data, run_id=scheduled__2024-07-04T00:00:00+00:00, execution_date=20240704T000000, start_date=20240708T172109, end_date=20240708T172115
[2024-07-08T17:21:15.999+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task insert_book_data (No book data found; 308)
[2024-07-08T17:21:16.074+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T17:21:16.371+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T17:21:16.422+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
