[2024-07-08T17:20:28.599+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T17:20:30.336+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-07-08T17:20:31.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-07-08T17:20:31.286+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T17:20:32.296+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-06-23 00:00:00+00:00
[2024-07-08T17:20:32.476+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=271) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T17:20:32.497+0000] {standard_task_runner.py:63} INFO - Started process 297 to run task
[2024-07-08T17:20:32.512+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'insert_book_data', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpzvsl880l']
[2024-07-08T17:20:32.519+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask insert_book_data
[2024-07-08T17:20:33.746+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-23T00:00:00+00:00 [running]> on host 75379950ed90
[2024-07-08T17:20:35.304+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-07-08T17:20:35.400+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T17:20:35.649+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T17:20:35.653+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 95, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-07-08T17:20:35.898+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=insert_book_data, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240708T172030, end_date=20240708T172035
[2024-07-08T17:20:36.273+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task insert_book_data (No book data found; 297)
[2024-07-08T17:20:36.518+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T17:20:37.181+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T17:20:37.285+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
