[2024-07-08T18:35:53.774+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T18:35:53.792+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data manual__2024-07-08T18:19:54.833403+00:00 [queued]>
[2024-07-08T18:35:53.797+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data manual__2024-07-08T18:19:54.833403+00:00 [queued]>
[2024-07-08T18:35:53.797+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-08T18:35:53.805+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-07-08 18:19:54.833403+00:00
[2024-07-08T18:35:53.816+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T18:35:53.817+0000] {standard_task_runner.py:63} INFO - Started process 286 to run task
[2024-07-08T18:35:53.818+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'insert_book_data', 'manual__2024-07-08T18:19:54.833403+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpmp4mi67t']
[2024-07-08T18:35:53.818+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask insert_book_data
[2024-07-08T18:35:53.851+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_amazon_books.insert_book_data manual__2024-07-08T18:19:54.833403+00:00 [running]> on host e7c2148586a4
[2024-07-08T18:35:53.898+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T18:19:54.833403+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T18:19:54.833403+00:00'
[2024-07-08T18:35:53.899+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T18:35:53.905+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T18:35:53.906+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 95, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-07-08T18:35:53.926+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_and_store_amazon_books, task_id=insert_book_data, run_id=manual__2024-07-08T18:19:54.833403+00:00, execution_date=20240708T181954, start_date=20240708T183553, end_date=20240708T183553
[2024-07-08T18:35:53.956+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 117 for task insert_book_data (No book data found; 286)
[2024-07-08T18:35:54.006+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T18:35:54.018+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T18:35:54.019+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
